# -*- coding: utf-8 -*-
"""RED WINE QUALITY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZKpDEaToujmko3wlEfUD6r7UwcJMoH6
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

wine_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Cognorise/winequality-red.csv')
wine_data

print(wine_data.head())

print(wine_data.head())

print(wine_data.isnull().sum())

plt.figure(figsize=(14, 7))
for i, column in enumerate(wine_data.columns[:-1]):
    plt.subplot(3, 4, i+1)
    sns.histplot(wine_data[column], kde=True)
    plt.title(f'{column} Distribution')

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(wine_data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()