# -*- coding: utf-8 -*-
"""UNEMPLOYMENT IN INDIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wI5SXE-V_sObieVLhYqV7mv64jwnOB2Y
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Cognorise/Unemployment in India.csv')
data

data.columns = data.columns.str.strip()

plt.figure(figsize=(15, 10))
regions = data['Region'].unique()[:5]
for region in regions:
    region_data = data[data['Region'] == region]
    plt.plot(region_data['Date'], region_data['Estimated Unemployment Rate (%)'], label=region)
plt.title('Unemployment Rate Trends Over Time for Selected Regions')
plt.xlabel('Date')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.legend(title='Region')
plt.grid(True)
plt.show()